services:
  mysql:
    image: mysql
    restart: always
    command:
      - 'mysqld'
      - '--secure-file-priv=/var/lib/mysql-files'
    environment:
      MYSQL_ROOT_PASSWORD: super-secret-password
      MYSQL_DATABASE: ray-tracing
    ports:
      - '3306:3306'

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: super-secret-password
    ports:
      - '5432:5432'