services:
  postgres:
    image: postgres
    restart: always
    command: >
      -c jit_above_cost=1
      -c jit_inline_above_cost=1
      -c jit_optimize_above_cost=1
      -c max_parallel_workers_per_gather=8
      -c max_worker_processes=8
      -c max_parallel_workers=8
      -c work_mem=256MB
      -c geqo_effort=10
    environment:
      POSTGRES_PASSWORD: super-secret-password
    ports:
      - '5432:5432'